### ISSUE TITLE
Does this use custom resolvers?

### ISSUE THREAD

**Issue by zkendall** [rtimush/sbt-updates#147]
I tried this plugin out and it only showed results for open-source libraries. None of our own internal dependencies showed up.

We have our resolvers set  like

```
import sbt._

object Common {
...
  val resolvers = Seq(
    "Nexus" at "https://OUR.INTERNAL.net/content/groups/public",
    "Twitter" at "https://maven.twttr.com"
  )
...
}
```

**Comment by rtimush** [comment]
In general, looking up updates in internal repositories should work without additional effort. For maven repositories, `sbt-updates` tries to download `maven-metadata.xml` (you can see this if you run `sbt --debug dependencyUpdates`). One possible reason could be that your Nexus server is not set up to rebuild the maven metadata. You can create a scheduled task in Nexus for that, or update metadata when publishing your internal artifacts by using something like [sbt-aether-deploy](https://github.com/arktekk/sbt-aether-deploy).

Potentially, `sbt-updates` can also apply the same heuristic as it uses for Ivy repositories where it parses the HTML output — this should be relatively easy to implement.

**Comment by mosche** [comment]
I was just looking into a similar issue for our private repos.
In our case it turns out that the request never reached Nexus behind Cloudflare. 

Cloudflare rejects requests with missing `User-Agent` header because of a `Browser Integrity Check` that's enabled by default. If that's the case for you, you might want to disable that check using a page rule.

**Comment by rtimush** [comment]
@mosche, thank you for the hint! I will check and add user agent to the requests the plugin makes.
